### ISSUE TITLE
overlapping signals in same message

### ISSUE THREAD

**Issue by varaha-Maithreya** [CSS-Electronics/can_decoder#10] opened 2023-01-30 23:38 UTC
Will this library handle overlapping signals in same message

**Comment by MatinF** [comment] 2023-01-31 06:52
Can you clarify what you mean?

**Comment by varaha-Maithreya** [comment] 2023-01-31 10:34
I was using cantools library before and I faced this error "signals {} and {} overlapping in message {}". 

Its due to multiple signals having same unique identification. Its something to do with dbc file.  I did some digging in the internet to find the below thread which pointed to this library.


https://stackoverflow.com/questions/71703715/how-to-handle-overlapped-signals-in-cantools-library


I cannot edit the dbc and change the duplicates as the manufacturer clearly wants overlapping signals.

**Comment by MatinF** [comment] 2023-01-31 10:45
It sounds like the issue is that your DBC may not be taking the multiplexing into account properly. Generally there should not be overlapping CAN signals unless the signals are multiplexed and thus distinguishable. I suggest reading our DBC intro and checking if there may be issues with the multiplexing setup (if that's what is intended) for your DBC. 

Let me know if this is related to a CANedge log file, if so we may be able to support further. Otherwise I'll be closing this.

**Closed as completed by MatinF** 2023-01-31 10:45 UTC
